###create new feature toggle
POST http://127.0.0.1:8080/feature-toggle/api/v1/features
Content-Type: application/json

{
  "display_name": "Example Display Name",
  "technical_name": "m2mo3",
  "description": "This is an example description.",
  "expires_on": "2024-12-31T23:59:59",
  "inverted": true,
  "customer_ids": [
    12,
    13
  ]
}

###update feature toggle
@technicalName =m2mo1
PUT http://localhost:8080/feature-toggle/api/v1/features/{{technicalName}}
Content-Type: application/json

{
  "display_name": "Updated",
  "technical_name": "m2mo1",
  "description": "This is an example description.",
  "expires_on": "2024-12-31T23:59:59",
  "inverted": true,
  "customer_ids": [
    10,
    11,
    12
  ]
}


### archive
PUT http://127.0.0.1:8080/feature-toggle/api/v1/operations/features/archive
Content-Type: application/json

[
  "m2mo2"
]

### release
PUT http://127.0.0.1:8080/feature-toggle/api/v1/operations/features/release
Content-Type: application/json

{
  "version_id": "v2",
  "description": "best version",
  "feature_toggle_names": [
    "m2mo1"
  ]
}

### search
POST http://127.0.0.1:8080/feature-toggle/api/v1/features/search
Content-Type: application/json

{
  "featureRequest": {
    "customerId": "12",
    "features": [
      {
        "name": "m2mo2"
      }
    ]
  }
}

### find all
GET http://localhost:8080/feature-toggle/api/v1/features?pageNo=0&pageSize=10

Content-Type: application/json
