spring:
  application:
    name: feature-toggle-web
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:h2:mem:featuretoggle;mode=mysql;
    password: ${feature-toggle.database.password}
    username: ${feature-toggle.database.username}
    name: ${feature-toggle.database.name}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
feature-toggle:
  database:
    name: featuretoggle
    username: sa
    password: password
    schema: dbo
