server:
  port: 8080
  servlet:
    context-path: /feature-toggle
spring:
  application:
    name: feature-toggle-web
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:h2:file:./feature_toggle_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;
    password: ${feature-toggle.database.password}
    username: ${feature-toggle.database.username}
    name: ${feature-toggle.database.name}
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  h2:
    console:
      enabled: true
feature-toggle:
  database:
    name: featuretoggle
    username: sa
    schema: dbo
  maxArchiveSize: 200
